// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateContact(arg1) {
  return window['go']['api']['Secure']['CreateContact'](arg1);
}

export function DeleteContact(arg1) {
  return window['go']['api']['Secure']['DeleteContact'](arg1);
}

export function FetchContact(arg1) {
  return window['go']['api']['Secure']['FetchContact'](arg1);
}

export function FetchContacts() {
  return window['go']['api']['Secure']['FetchContacts']();
}

export function Login(arg1, arg2) {
  return window['go']['api']['Secure']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['api']['Secure']['Logout']();
}

export function UpdateContact(arg1, arg2) {
  return window['go']['api']['Secure']['UpdateContact'](arg1, arg2);
}
