/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Crud: typeof import('./components/crud.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Jaxb: typeof import('./components/jaxb.vue')['default']
    Login: typeof import('./components/login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackbarProvider: typeof import('./components/SnackbarProvider.vue')['default']
    Soap: typeof import('./components/soap.vue')['default']
    Startpage: typeof import('./components/startpage.vue')['default']
    Validation: typeof import('./components/validation.vue')['default']
    Weather: typeof import('./components/weather.vue')['default']
  }
}
