// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {main} from '../models';

export function FetchWeather(arg1:string):Promise<Array<api.CityWeatherInfo>>;

export function Greet(arg1:string):Promise<string>;

export function Validate(arg1:main.JsFile,arg2:string,arg3:string):Promise<main.Response>;
