// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSoapFileExists() {
  return window['go']['main']['App']['CheckSoapFileExists']();
}

export function FetchWeather(arg1) {
  return window['go']['main']['App']['FetchWeather'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ManualSearch(arg1) {
  return window['go']['main']['App']['ManualSearch'](arg1);
}

export function RunJaxbValidation(arg1) {
  return window['go']['main']['App']['RunJaxbValidation'](arg1);
}

export function Validate(arg1, arg2, arg3) {
  return window['go']['main']['App']['Validate'](arg1, arg2, arg3);
}
