// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchWeather(arg1) {
  return window['go']['main']['App']['FetchWeather'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SearchContacts(arg1) {
  return window['go']['main']['App']['SearchContacts'](arg1);
}

export function Validate(arg1, arg2, arg3) {
  return window['go']['main']['App']['Validate'](arg1, arg2, arg3);
}
